name: xpcs
channels:
  - conda-forge
  - defaults
  - esrf-bcu
dependencies:
  - python
  - numpy
  - h5py
  - hdf5plugin
  - time
  - ipywidgets
  - ipython
  - matplotlib
  - ca-certificates
  - openssl
  - ipykernel
  - certifi
  - scipy
  - tifffile
  - scikit-learn
  - pandas
  - opencv
  - nbformat
  - pyopencl
  - joblib
  - ase
  - xrayutilities
  - xraydb
  - numba
  - noise
  - imageio
  - opensimplex
  - ipympl
  - cmcrameri
  - scikit-beam
  - argcomplete
prefix: /Users/eriklamb/miniforge3/envs/xpcs
